// Nicholas Saylor 10/28/2021
// CMPEN 270 Verilog Project 8
// YOSYS Gate-Level file for LS74163 counter


/* Generated by Yosys 0.5 (git sha1 c3c9fbf, i686-pc-mingw32-gcc 4.8.1 -Os) */

module LS74163(CLR_L, LD_L, ENT, ENP, CLK, QD, QC, QB, QA, D, C, B, A);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input A;
  input B;
  input C;
  input CLK;
  input CLR_L;
  input D;
  input ENP;
  input ENT;
  input LD_L;
  output QA;
  output QB;
  output QC;
  output QD;
  INV _17_ (
    .A(QC),
    .Z(_04_)
  );
  AND2 _18_ (
    .A(ENP),
    .B(ENT),
    .Z(_05_)
  );
  NAND3 _19_ (
    .A(_05_),
    .B(QA),
    .C(QB),
    .Z(_06_)
  );
  XNOR _20_ (
    .A(_06_),
    .B(_04_),
    .Z(_07_)
  );
  OAI21 _21_ (
    .A1(LD_L),
    .A2(C),
    .B(CLR_L),
    .Z(_08_)
  );
  AOI21 _22_ (
    .A1(_07_),
    .A2(LD_L),
    .B(_08_),
    .Z(_02_)
  );
  NOR2 _23_ (
    .A(_06_),
    .B(_04_),
    .Z(_09_)
  );
  XNOR _24_ (
    .A(_09_),
    .B(QD),
    .Z(_10_)
  );
  OAI21 _25_ (
    .A1(D),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_11_)
  );
  AOI21 _26_ (
    .A1(_10_),
    .A2(LD_L),
    .B(_11_),
    .Z(_03_)
  );
  XNOR _27_ (
    .A(_05_),
    .B(QA),
    .Z(_12_)
  );
  OAI21 _28_ (
    .A1(A),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_13_)
  );
  AOI21 _29_ (
    .A1(_12_),
    .A2(LD_L),
    .B(_13_),
    .Z(_00_)
  );
  NAND2 _30_ (
    .A(_05_),
    .B(QA),
    .Z(_14_)
  );
  XOR _31_ (
    .A(_14_),
    .B(QB),
    .Z(_15_)
  );
  OAI21 _32_ (
    .A1(B),
    .A2(LD_L),
    .B(CLR_L),
    .Z(_16_)
  );
  AOI21 _33_ (
    .A1(_15_),
    .A2(LD_L),
    .B(_16_),
    .Z(_01_)
  );
  FFD _34_ (
    .CK(CLK),
    .D(_03_),
    .Q(QD)
  );
  FFD _35_ (
    .CK(CLK),
    .D(_02_),
    .Q(QC)
  );
  FFD _36_ (
    .CK(CLK),
    .D(_01_),
    .Q(QB)
  );
  FFD _37_ (
    .CK(CLK),
    .D(_00_),
    .Q(QA)
  );
endmodule
